import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'it' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  it: {
    // Navigation
    'nav.services': 'Servizi',
    'nav.rentcar': 'Noleggia Auto',
    'nav.yacht': 'Yacht',
    'nav.villas': 'Ville',
    'nav.detailing': 'Premium Car Detailing',
    'nav.rapidservices': 'Servizi Rapidi Auto',
    'nav.contact': 'Contatti',
    
    // Hero
    'hero.title': 'Esperienza Esclusiva',
    'hero.subtitle': 'Scopri il mondo dei exotic cars, yacht, jet privati e ville esclusive',
    'hero.cta': 'Esplora i Nostri Servizi',
    'hero.scroll': 'Scorri per scoprire',
    
    'services.title': 'I Nostri Servizi',
    'services.supercars': 'Exotic Cars',
    'services.yachts': 'Yachts',
    'services.jets': 'Jet Privati',
    'services.villas': 'Ville',
    'services.helicopters': 'Elicotteri',
    'services.membership': 'Membership VIP',
    'services.detailing': 'Car Detailing Premium',
    'services.mechanical': 'Servizi Meccanici',
    
    // Contact
    'contact.title': 'Contatti',
    'contact.whatsapp': 'WhatsApp',
    'contact.office': 'Orari ufficio: 9:00 - 20:00',
    
    // Auth
    'auth.welcome': 'Benvenuti in DR7 Exotic',
    'auth.subtitle': 'Accedi al tuo account di noleggio',
    'auth.signin': 'Accedi',
    'auth.signup': 'Registrati', 
    'auth.signin.title': 'Accedi',
    'auth.signin.desc': 'Inserisci le tue credenziali per accedere al tuo account',
    'auth.signup.title': 'Crea Account',
    'auth.signup.desc': 'Unisciti a DR7 Exotic per noleggi esclusivi',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.forgotpassword': 'Password dimenticata?',
    'auth.signingin': 'Accesso in corso...',
    'auth.creatingaccount': 'Creazione account in corso...',
    'auth.createaccount': 'Crea Account',
    'auth.continuewithgoogle': 'Continua con Google',
    'auth.continuewithfacebook': 'Continua con Facebook',
    'auth.acceptterms': 'Accetto i',
    'auth.termsofservice': 'Termini di Servizio',
    'auth.and': 'e la',
    'auth.privacypolicy': 'Privacy Policy',
    'auth.minchars': 'Minimo 6 caratteri',
    
    // Rentals
    'rentals.title': 'Noleggia un\'auto',
    'rentals.backto': 'Torna alla Home',
    'rentals.needhelp': 'Hai Bisogno di Aiuto?',
    'rentals.helpdesc': 'Il nostro team concierge è disponibile 24/7 per aiutarti a scegliere il veicolo perfetto.',
    'rentals.contactconcierge': 'Contatta il Nostro Concierge',
    'rentals.booknow': 'Prenota Ora',
    'rentals.notavailable': 'Non Disponibile',
    
    // Services
    'services.rapidservices': 'Servizi Rapidi',
    'services.rapiddesc': 'Prezzi competitivi per servizi rapidi e professionali',
    'services.rapidsubtitle': 'Servizi automobilistici rapidi, affidabili e professionali di cui ti puoi fidare.',
    'services.ourservices': 'I Nostri Servizi',
    'services.ourservicesdesc': 'Servizi automobilistici professionali con prezzi trasparenti',
    'services.brakepad': 'Sostituzione Pastiglie Freno',
    'services.brakepadDesc': 'Manutenzione freni professionale per la tua sicurezza',
    'services.oilservice': 'Servizio Olio Express',
    'services.oilserviceDesc': 'Olio + filtri con controllo livello fluidi',
    'services.wiperblade': 'Sostituzione Spazzole Tergicristallo',
    'services.wiperbladeDesc': 'Visione chiara in tutte le condizioni meteorologiche',
    'services.battery': 'Sostituzione Batteria',
    'services.batteryDesc': 'Alimentazione affidabile per il tuo veicolo',
    'services.bulb': 'Sostituzione Lampadine',
    'services.bulbDesc': 'Soluzioni di illuminazione professionali',
    'services.quickmech': 'Riparazioni Meccaniche Rapide',
    'services.quickmechDesc': 'Servizi meccanici rapidi e affidabili',
    'services.needservice': 'Hai Bisogno di un Servizio?',
    'services.needservicedesc': 'Contattaci per programmare il tuo servizio automobilistico oggi.',
    'services.bookservicenow': 'Prenota Servizio Ora',

    // Yacht Rental
    'yacht.title': 'DR7 Yacht',
    'yacht.subtitle': 'Vivi l\'esperienza definitiva sulle acque cristalline della Sardegna',
    'yacht.packages': 'Pacchetti di Noleggio',
    'yacht.packagesdesc': 'Scegli la tua esperienza yacht perfetta',
    'yacht.persons': 'persone',
    'yacht.additionalguest': 'per ogni ospite aggiuntivo',
    'yacht.included': 'Servizi Inclusi in Entrambe le Formule',
    'yacht.extraservices': 'Servizi Extra su Richiesta',
    'yacht.extraservicesdesc': 'Arricchisci la tua esperienza yacht con servizi premium',
    'yacht.needhelp': 'Hai Bisogno di Aiuto per Pianificare la Tua Esperienza?',
    'yacht.personalservice': 'Il nostro team concierge è qui per creare la tua esperienza yacht perfetta',
    'yacht.contactus': 'Contatta il Nostro Concierge',
    'services.important': 'Importante:',
    'services.importantnote': 'Questi prezzi si riferiscono solo alla manodopera. I pezzi verranno forniti dal cliente o acquistati separatamente.',
    'services.front': 'Anteriore',
    'services.rear': 'Posteriore',
    'services.frontplusrear': 'Anteriore + Posteriore',
    'services.citycars': 'Auto cittadine',
    'services.sedansuvs': 'Berline/SUV',
    'services.luxurysports': 'Auto sportive',
    'services.frontpair': 'Coppia anteriore',
    'services.rearif': 'Posteriore (se presente)',
    'services.standardbulb': 'Lampadina standard',
    'services.ledxenon': 'LED/Xenon',
    'services.wiperarms': 'Bracci tergicristallo',
    'services.suspensionarms': 'Bracci sospensioni (accesso facile)',
    'services.aircabinfilter': 'Sostituzione filtro aria/abitacolo',
    
    // Detailing
    'detailing.premiumdetailing': 'Car Detailing Premium',
    'detailing.subtitle': 'Servizi di Lavaggio Auto Veloci e Premium – Nessun Appuntamento Necessario',
    'detailing.tagline': 'Per un look pulito e dettagliato ogni giorno. Scegli eccellenza, velocità e qualità.',
    'detailing.washpackages': 'Pacchetti Lavaggio',
    'detailing.washpackagesdesc': 'Servizi di lavaggio auto premium con prodotti e tecniche di alto livello',
    'detailing.fullclean': 'PULIZIA COMPLETA',
    'detailing.fullcleandesc': 'Pulizia essenziale per l\'eccellenza quotidiana.',
    'detailing.topshine': 'BRILLANTEZZA SUPERIORE',
    'detailing.topshinedesc': 'Protezione migliorata con finitura premium.',
    'detailing.vipexperience': 'ESPERIENZA VIP',
    'detailing.vipexperiencedesc': 'Cura completa con extra premium.',
    'detailing.dr7luxury': 'DR7 PREMIUM',
    'detailing.dr7luxurydesc': 'L\'esperienza di detailing definitiva.',
    'detailing.courtesycar': 'Auto di Cortesia / Esperienza Exotic Car',
    'detailing.courtesycar.subtitle': 'Mentre la tua auto è nel nostro detailing center.',
    'detailing.supercarexp': 'Esperienza Exotic Car',
    'detailing.supercarexpsubtitle': 'Senti il brivido delle prestazioni',
    'detailing.supercarexpdesc': 'Vivi la nostra collezione di exotic cars premium.',
    'detailing.ferrarilambo': 'Ferrari e Lamborghini',
    'detailing.ferrarilambosub': 'Guida una delle nostre exotic cars top mentre riportiamo in vita la tua',
    'detailing.ferrarilambodesc': 'L\'esperienza definitiva con i nostri veicoli di punta.',
    'detailing.needhelpchoose': 'Hai Bisogno di Aiuto nella Scelta?',
    'detailing.needhelpchoosedesc': 'Il nostro team è disponibile 24/7 per aiutarti a selezionare il servizio perfetto per le tue esigenze.',
    'detailing.contactteam': 'Contatta il Nostro Team',
    
    // 404
    'notfound.title': '404',
    'notfound.subtitle': 'Ops! Pagina non trovata',
    'notfound.returnhome': 'Torna alla Home',
    'contact.cta': 'Lascia che curiamo il tuo prossimo viaggio indimenticabile.',
    
    // Buttons
    'btn.booknow': 'Prenota Ora',
    'btn.learnmore': 'Scopri di più',
    'btn.contact': 'Contattaci',
    'btn.whatsapp': 'WhatsApp',
    'btn.back': 'Indietro',
    
    // Footer
    'footer.services': 'Servizi',
    'footer.company': 'Azienda',
    'footer.support': 'Supporto',
    'footer.about': 'Chi Siamo',
    'footer.howitworks': 'Come Funziona',
    'footer.terms': 'Termini di Servizio',
    'footer.whatsappsupport': 'Supporto WhatsApp',
    'footer.rights': '© 2024 Dubai Rent 7.0 S.p.A. Tutti i diritti riservati.',
    
    // Car descriptions
    'car.bmwm3': 'Un\'icona che domina la strada.',
    'car.audirs3': 'Impossibile passare inosservati.',
    'car.porsche911': 'La firma eterna di Porsche.',
    'car.hummer': 'Presenza leggendaria su strada.',
    'car.mercedesgle': 'Nato per distinguersi.',
    'car.mercedesa45': 'Compatta ma selvaggia.',
    'car.bmwm4': 'Performance iconiche con stile.',
    'car.urus': 'Intrepida su ogni strada.',
    'car.ferrari': 'Sogno italiano a cielo aperto.',
    'car.bmwm2': 'Performance pura e drammatica.',
    'car.audirs3red': 'Eleganza incontra la potenza grezza.',
    'car.macan': 'Eleganza da corsa.',
    'car.c63': 'Il re dei SUV urbani.',
    'car.alfa': 'M Power incontra l\'utilità.',
    'car.ducato': 'Pronto a trasportare tutto.',
    
    // Services Page
    'services.page.title': 'Servizi Premium',
    'services.page.subtitle': 'Esperienza e qualità senza compromessi',
    'services.exteriorwash': 'Lavaggio Esterno',
    'services.interiordetail': 'Detailing Interni',
    'services.fulldetail': 'Detailing Completo',
    'services.carcare': 'Cura Auto Premium',
    'services.maintenance': 'Manutenzione',
    'services.diagnostics': 'Diagnostica',
    
    // Cookie Consent
    'cookie.title': 'Impostazioni Privacy',
    'cookie.description': 'Utilizziamo i cookie per migliorare la tua esperienza. Puoi scegliere quali categorie accettare.',
    'cookie.essential': 'Cookie Essenziali',
    'cookie.essential.desc': 'Necessari per il funzionamento del sito',
    'cookie.analytics': 'Cookie Analitici',
    'cookie.analytics.desc': 'Ci aiutano a migliorare il nostro sito',
    'cookie.marketing': 'Cookie di Marketing',
    'cookie.marketing.desc': 'Utilizzati per mostrare annunci pertinenti',
    'cookie.acceptall': 'Accetta Tutto',
    'cookie.decline': 'Rifiuta',
    'cookie.customize': 'Personalizza',
    'cookie.save': 'Salva Preferenze',
    
    // Age Verification
    'ageVerification.title': 'Hai più di 18 anni?',
    'ageVerification.messageIt': 'Per entrare nel sito DR7 Exotic, conferma di avere almeno 18 anni.',
    'ageVerification.messageEn': 'To access DR7 Exotic, please confirm you\'re over 18.',
    'ageVerification.yes': 'Sì, ho più di 18 anni',
    'ageVerification.no': 'No, ho meno di 18 anni',
    
    // Lottery Modal
    'lottery.messageIt': 'Hai 20€. Hai un clic. Hai la possibilità di portarti a casa una Lamborghini nuova da 400.000€.',
    'lottery.messageEn': 'You have €20. One click. You could win a brand-new Lamborghini worth €400,000.',
    'lottery.close': 'Chiudi',
    'lottery.joinButton': 'Partecipa',
    'lottery.comingSoon': 'Prossimamente',
    'lottery.back': 'Indietro',
    'lottery.heroText': 'Partecipa alla lotteria più esclusiva d\'Italia. Con soli 20€ puoi vincere una delle 19 exotic cars in palio per un valore totale di oltre 3 milioni di euro.',
    'lottery.ticketTitle': 'Il Tuo Biglietto',
    'lottery.prizePoolTitle': 'Exotic Cars in Palio',
    'lottery.totalValue': 'Valore Totale: Oltre €3.000.000',
    'lottery.rulesTitle': 'Regolamento',
    'lottery.rule1': 'Il costo del biglietto è di €20',
    'lottery.rule2': 'Estrazione pubblica il 30 ottobre 2025 con notaio e avvocato',
    'lottery.rule3': 'Valido solo con ricevuta ufficiale',
    'lottery.rule4': 'I biglietti sono limitati e numerati',
    'lottery.rule5': 'Il vincitore sarà contattato entro 24 ore dall\'estrazione',
    'lottery.rule6': 'Tutti i veicoli sono nuovi e con garanzia ufficiale',
    'lottery.ctaTitle': 'Non Perdere Questa Opportunità Unica',
    'lottery.ctaText': 'Acquista il tuo biglietto ora e potresti guidare a casa la exotic car dei tuoi sogni.',
    
    // Mileage rules
    'mileage.title': 'Kilometri Inclusi',
    'mileage.day1': '1 giorno → 100 km',
    'mileage.day2': '2 giorni → 180 km',
    'mileage.day3': '3 giorni → 240 km',
    'mileage.day4': '4 giorni → 280 km',
    'mileage.day5': '5 giorni → 300 km',
    'mileage.day6Plus': 'Dal 6° giorno in poi → +60 km al giorno',
    'mileage.yourRental': 'La tua prenotazione di {days} giorni include {km} km',
    
    // Villa Listings & Details
    'villa.listings.title': 'Ville di Lusso',
    'villa.listings.subtitle': 'Scopri le nostre ville esclusive con servizi concierge 24/7',
    'villa.listings.discoverMore': 'Scopri di più',
    'villa.listings.perNight': 'per notte',
    'villa.listings.notFoundTitle': 'Non trovi la villa perfetta?',
    'villa.listings.notFoundDesc': 'Il nostro team concierge può aiutarti a trovare l\'alloggio ideale per le tue esigenze',
    'villa.listings.contactConcierge': 'Contatta il Concierge',
    
    'villa.details.theVilla': 'La Villa',
    'villa.details.comfortServices': 'Comfort e Servizi',
    'villa.details.interiorSpaces': 'Spazi Interni',
    'villa.details.position': 'Posizione',
    'villa.details.extraServices': 'Servizi Extra (su richiesta)',
    'villa.details.guests': 'ospiti',
    'villa.details.rooms': 'camere',
    'villa.details.bathrooms': 'bagni',
    'villa.details.checkIn': 'Check-in',
    'villa.details.checkOut': 'Check-out',
    'villa.details.select': 'Seleziona',
    'villa.details.bookNow': 'Contattaci',
    'villa.details.instantConfirm': 'Conferma istantanea via WhatsApp',
    'villa.details.cleaning': 'Pulizie',
    'villa.details.serviceFee': 'Commissioni servizio',
    'villa.details.total': 'Totale',
    'villa.details.nights': 'notti',
    'villa.details.questionsTitle': 'Hai domande su Villa Ambra?',
    'villa.details.questionsDesc': 'Il nostro team concierge è disponibile 24/7 per assistenza personalizzata e servizi esclusivi',
    'villa.details.contactTeam': 'Contatta il Nostro Concierge',
    'villa.details.bookingTitle': 'Prenotazione',
    'villa.details.selectDates': 'Seleziona le date per richiedere informazioni',
    'villa.amenities': 'Amenities',
    
    // Payment translations
    'securePayment': 'Pagamento Sicuro',
    'paymentAmount': 'Importo',
    'secureTransaction': 'Transazione Sicura',
    'sslEncrypted': 'Crittografia SSL',
    'pciCompliant': 'Conforme PCI DSS',
    'nexiPaymentDescription': 'Sarai reindirizzato al gateway di pagamento sicuro Nexi.',
    'cardTypesAccepted': 'Accettiamo Visa, Mastercard e altre carte principali.',
    'payNow': 'Paga Ora',
    'processing': 'Elaborazione...',
    'nexiPowered': 'Powered by Nexi',
    'paymentInitiated': 'Pagamento Avviato',
    'redirectedToNexi': 'Stai per essere reindirizzato al gateway di pagamento Nexi.',
    'paymentError': 'Errore di Pagamento',
    'paymentSuccessful': 'Pagamento Riuscito!',
    'bookingConfirmed': 'La tua prenotazione è stata confermata e il pagamento elaborato con successo.',
    'orderSummary': 'Riepilogo Ordine',
    'vehicle': 'Veicolo',
    'transactionId': 'ID Transazione',
    'pickupDate': 'Data Ritiro',
    'dropoffDate': 'Data Consegna',
    'totalPaid': 'Totale Pagato',
    'nextSteps': 'Prossimi Passi',
    'confirmationEmailSent': 'Una email di conferma è stata inviata al tuo indirizzo.',
    'contractWillBeSent': 'Il contratto di noleggio sarà inviato entro 24 ore.',
    'prepareDocuments': 'Prepara la patente e documento di identità per il ritiro.',
    'viewBookings': 'Visualizza le Mie Prenotazioni',
    'backToHome': 'Torna alla Home',
    'supportMessage': 'Hai bisogno di aiuto? Contatta il nostro team di supporto:',
    'paymentFailed': 'Pagamento Fallito',
    'paymentFailedDescription': 'Non siamo riusciti a elaborare il tuo pagamento.',
    'paymentNotProcessed': 'Sfortunatamente, il tuo pagamento non può essere elaborato.',
    'errorDetails': 'Dettagli Errore',
    'errorCode': 'Codice Errore',
    'errorMessage': 'Messaggio di Errore',
    'possibleSolutions': 'Possibili Soluzioni',
    'checkCardDetails': 'Verifica che i dettagli della carta siano corretti',
    'checkCardBalance': 'Assicurati che la carta abbia saldo sufficiente',
    'tryDifferentCard': 'Prova a utilizzare una carta diversa',
    'contactBank': 'Contatta la tua banca se il problema persiste',
    'retryPayment': 'Riprova Pagamento',
    'needHelp': 'Hai Bisogno di Aiuto?',
    'supportDescription': 'Il nostro team di assistenza clienti è qui per aiutarti a risolvere qualsiasi problema di pagamento.',
    'includeTransactionId': 'Includi questo ID transazione quando contatti il supporto',
    'securityNotice': 'I dettagli della tua carta sono sicuri e non sono stati memorizzati sui nostri server.',
    'cardDeclined': 'Carta rifiutata dalla banca emittente',
    'insufficientFunds': 'Fondi insufficienti',
    'invalidCard': 'Numero carta non valido',
    'expiredCard': 'Carta scaduta',
    'authenticationFailed': 'Autenticazione fallita',
    'transactionTimeout': 'Timeout transazione',
    'systemError': 'Errore di sistema, riprova',
    'duplicateTransaction': 'Transazione duplicata',
    'securityViolation': 'Violazione di sicurezza rilevata',
    'cardNotSupported': 'Tipo di carta non supportato',
    'unknownPaymentError': 'Errore di pagamento sconosciuto',
    
    // Inline Eligibility Selectors
    'validation.ageRequired': 'Conferma la tua fascia d\'età.',
    'validation.countryRequired': 'Seleziona il tuo paese.',
    'validation.ageInconsistent.title': 'Età non corrispondente',
    'validation.ageInconsistent.message': 'L\'età selezionata non coincide con la data di nascita.',
    'validation.ageInconsistent.short': 'Età non corrispondente alla data di nascita.',

    // Reviews
    'reviews.title': 'Recensioni dei Clienti',
    'reviews.subtitle': 'Cosa dicono i nostri clienti della loro esperienza',
    'reviews.error': 'Errore nel caricamento delle recensioni',
    'reviews.retry': 'Riprova',
    'reviews.noReviews': 'Nessuna recensione disponibile',
    'reviews.topRated': 'Migliori Recensioni (4+ ⭐)',
    'reviews.allReviews': 'Tutte le Recensioni',
    'reviews.seeAllOnGoogle': 'Vedi tutte su Google',
    'reviews.previous': 'Precedente',
    'reviews.next': 'Successiva',
    'reviews.goToReview': 'Vai alla recensione',
  },
  en: {
    // Navigation
    'nav.services': 'Services',
    'nav.rentcar': 'Rent a Car',
    'nav.yacht': 'Yacht',
    'nav.villas': 'Villas',
    'nav.detailing': 'Premium Car Detailing',
    'nav.rapidservices': 'Rapid Car Services',
    'nav.contact': 'Contact',
    
    // Hero
    'hero.title': 'Exclusive Experience',
    'hero.subtitle': 'Discover the world of exotic cars, yachts, private jets and exclusive villas',
    'hero.cta': 'Explore Our Services',
    'hero.scroll': 'Scroll to discover',
    
    'services.title': 'Our Services',
    'services.supercars': 'Exotic Cars',
    'services.yachts': 'Yachts',
    'services.jets': 'Private Jets',
    'services.villas': 'Villas',
    'services.helicopters': 'Helicopters',
    'services.membership': 'VIP Membership',
    'services.detailing': 'Premium Car Detailing',
    'services.mechanical': 'Mechanical Services',
    
    // Contact
    'contact.title': 'Contact',
    'contact.whatsapp': 'WhatsApp',
    'contact.office': 'Office hours: 9am to 8pm',
    
    // Auth
    'auth.welcome': 'Welcome to DR7 Exotic',
    'auth.subtitle': 'Access your rental account',
    'auth.signin': 'Sign In',
    'auth.signup': 'Sign Up', 
    'auth.signin.title': 'Sign In',
    'auth.signin.desc': 'Enter your credentials to access your account',
    'auth.signup.title': 'Create Account',
    'auth.signup.desc': 'Join DR7 Exotic for exclusive rentals',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.forgotpassword': 'Forgot password?',
    'auth.signingin': 'Signing in...',
    'auth.creatingaccount': 'Creating account...',
    'auth.createaccount': 'Create Account',
    'auth.continuewithgoogle': 'Continue with Google',
    'auth.continuewithfacebook': 'Continue with Facebook',
    'auth.acceptterms': 'I accept the',
    'auth.termsofservice': 'Terms of Service',
    'auth.and': 'and',
    'auth.privacypolicy': 'Privacy Policy',
    'auth.minchars': 'Minimum 6 characters',
    
    // Rentals
    'rentals.title': 'Rent a car',
    'rentals.backto': 'Back to Home',
    'rentals.needhelp': 'Need Help Choosing?',
    'rentals.helpdesc': 'Our concierge team is available 24/7 to help you select the perfect vehicle for your needs.',
    'rentals.contactconcierge': 'Contact Our Concierge',
    'rentals.booknow': 'Book Now',
    'rentals.notavailable': 'Not Available',
    
    // Services
    'services.rapidservices': 'Rapid Services',
    'services.rapiddesc': 'Competitive pricing for fast and professional services',
    'services.rapidsubtitle': 'Quick, reliable, and professional automotive services you can trust.',
    'services.ourservices': 'Our Services',
    'services.ourservicesdesc': 'Professional automotive services with transparent pricing',
    'services.brakepad': 'Brake Pad Replacement',
    'services.brakepadDesc': 'Professional brake maintenance for your safety',
    'services.oilservice': 'Express Oil Service',
    'services.oilserviceDesc': 'Oil + filters with fluid level check',
    'services.wiperblade': 'Wiper Blade Replacement',
    'services.wiperbladeDesc': 'Clear vision in all weather conditions',
    'services.battery': 'Battery Replacement',
    'services.batteryDesc': 'Reliable power for your vehicle',
    'services.bulb': 'Bulb Replacement',
    'services.bulbDesc': 'Professional lighting solutions',
    'services.quickmech': 'Quick Mechanical Fixes',
    'services.quickmechDesc': 'Fast and reliable mechanical services',
    'services.needservice': 'Need a Service?',
    'services.needservicedesc': 'Contact us to schedule your automotive service today.',
    'services.bookservicenow': 'Book Service Now',

    // Yacht Rental
    'yacht.title': 'DR7 Yacht',
    'yacht.subtitle': 'Experience the ultimate on the crystal waters of Sardegna',
    'yacht.packages': 'Rental Packages',
    'yacht.packagesdesc': 'Choose your perfect yacht experience',
    'yacht.persons': 'persons',
    'yacht.additionalguest': 'per additional guest',
    'yacht.included': 'Services Included in Both Packages',
    'yacht.extraservices': 'Extra Services on Request',
    'yacht.extraservicesdesc': 'Enhance your yacht experience with premium services',
    'yacht.needhelp': 'Need Help Planning Your Experience?',
    'yacht.personalservice': 'Our concierge team is here to create your perfect yacht experience',
    'yacht.contactus': 'Contact Our Concierge',
    'services.important': 'Important:',
    'services.importantnote': 'These prices refer to labor only. Parts will either be supplied by the customer or purchased separately.',
    'services.front': 'Front',
    'services.rear': 'Rear',
    'services.frontplusrear': 'Front + Rear',
    'services.citycars': 'City cars',
    'services.sedansuvs': 'Sedans/SUVs',
    'services.luxurysports': 'Sports cars',
    'services.frontpair': 'Front pair',
    'services.rearif': 'Rear (if present)',
    'services.standardbulb': 'Standard bulb',
    'services.ledxenon': 'LED/Xenon',
    'services.wiperarms': 'Wiper arms',
    'services.suspensionarms': 'Suspension arms (easy access)',
    'services.aircabinfilter': 'Air/Cabin filter replacement',
    
    // Detailing
    'detailing.premiumdetailing': 'Premium Car Detailing',
    'detailing.subtitle': 'Fast & Premium Car Wash Services – No Appointment Needed',
    'detailing.tagline': 'For a clean, detailed look every day. Choose excellence, speed, and quality.',
    'detailing.washpackages': 'Wash Packages',
    'detailing.washpackagesdesc': 'Premium car wash services with high-grade products and techniques',
    'detailing.fullclean': 'FULL CLEAN',
    'detailing.fullcleandesc': 'Essential cleaning for everyday excellence.',
    'detailing.topshine': 'TOP SHINE',
    'detailing.topshinedesc': 'Enhanced protection with premium finishing.',
    'detailing.vipexperience': 'VIP EXPERIENCE',
    'detailing.vipexperiencedesc': 'Comprehensive care with premium extras.',
    'detailing.dr7luxury': 'DR7 PREMIUM',
    'detailing.dr7luxurydesc': 'The ultimate detailing experience.',
    'detailing.courtesycar': 'Courtesy Car / Exotic Car Experience',
    'detailing.courtesycar.subtitle': 'While your car is in our detailing center.',
    'detailing.supercarexp': 'Exotic Car Experience',
    'detailing.supercarexpsubtitle': 'Feel the thrill of performance',
    'detailing.supercarexpdesc': 'Experience our premium exotic car collection.',
    'detailing.ferrarilambo': 'Ferrari and Lamborghini',
    'detailing.ferrarilambosub': 'Drive one of our top exotic cars while we bring yours back to life',
    'detailing.ferrarilambodesc': 'The ultimate experience with our flagship vehicles.',
    'detailing.needhelpchoose': 'Need Help Choosing?',
    'detailing.needhelpchoosedesc': 'Our team is available 24/7 to help you select the perfect service for your needs.',
    'detailing.contactteam': 'Contact Our Team',
    
    // 404
    'notfound.title': '404',
    'notfound.subtitle': 'Oops! Page not found',
    'notfound.returnhome': 'Return to Home',
    'contact.cta': 'Let us curate your next unforgettable journey.',
    
    // Reviews section  
    'reviews.title': 'Customer Reviews',
    'reviews.subtitle': 'What our clients say about their experience',
    'reviews.topRated': 'Top Rated (4+ ⭐)',
    'reviews.allReviews': 'All Reviews',
    'reviews.seeAllOnGoogle': 'See all on Google',
    'reviews.previous': 'Previous',
    'reviews.next': 'Next',
    'reviews.goToReview': 'Go to review',
    'reviews.error': 'Error loading reviews',
    'reviews.noReviews': 'No reviews available',
    'reviews.retry': 'Retry',
    
    // Buttons
    'btn.booknow': 'Book Now',
    'btn.learnmore': 'Learn More',
    'btn.contact': 'Contact Us',
    'btn.whatsapp': 'WhatsApp',
    'btn.back': 'Back to Home',
    
    // Footer
    'footer.services': 'Services',
    'footer.company': 'Company',
    'footer.support': 'Support',
    'footer.about': 'About Us',
    'footer.howitworks': 'How It Works',
    'footer.terms': 'Terms of Service',
    'footer.whatsappsupport': 'WhatsApp Support',
    'footer.rights': '© 2024 Dubai Rent 7.0 S.p.A. All rights reserved.',
    
    // Car descriptions
    'car.bmwm3': 'An icon that dominates the road.',
    'car.audirs3': 'Impossible to go unnoticed.',
    'car.porsche911': 'The eternal signature of Porsche.',
    'car.hummer': 'Legendary road presence.',
    'car.mercedesgle': 'Born to stand out.',
    'car.mercedesa45': 'Compact but wild.',
    'car.bmwm4': 'Iconic performance in style.',
    'car.urus': 'Fearless on any road.',
    'car.ferrari': 'Open-top Italian dream.',
    'car.bmwm2': 'Pure performance and drama.',
    'car.audirs3red': 'Elegance meets raw power.',
    'car.macan': 'Race-bred elegance.',
    'car.c63': 'The king of urban SUVs.',
    'car.alfa': 'M Power meets utility.',
    'car.ducato': 'Ready to carry it all.',
    
    // Services Page
    'services.page.title': 'Premium Services',
    'services.page.subtitle': 'Experience and uncompromising quality',
    'services.exteriorwash': 'Exterior Wash',
    'services.interiordetail': 'Interior Detailing',
    'services.fulldetail': 'Full Detailing',
    'services.carcare': 'Premium Car Care',
    'services.maintenance': 'Maintenance',
    'services.diagnostics': 'Diagnostics',
    
    // Cookie Consent
    'cookie.title': 'Privacy Settings',
    'cookie.description': 'We use cookies to improve your experience. You can choose which categories to accept.',
    'cookie.essential': 'Essential Cookies',
    'cookie.essential.desc': 'Required for the site to function',
    'cookie.analytics': 'Analytics Cookies',
    'cookie.analytics.desc': 'Help us improve our website',
    'cookie.marketing': 'Marketing Cookies',
    'cookie.marketing.desc': 'Used to show relevant advertisements',
    'cookie.acceptall': 'Accept All',
    'cookie.decline': 'Decline',
    'cookie.customize': 'Customize',
    'cookie.save': 'Save Preferences',
    
    // Age Verification
    'ageVerification.title': 'Are you over 18?',
    'ageVerification.messageIt': 'Per entrare nel sito DR7 Exotic, conferma di avere almeno 18 anni.',
    'ageVerification.messageEn': 'To access DR7 Exotic, please confirm you\'re over 18.',
    'ageVerification.yes': 'Yes, I\'m over 18',
    'ageVerification.no': 'No, I\'m under 18',
    
    // Lottery Modal
    'lottery.messageIt': 'Hai 20€. Hai un clic. Hai la possibilità di portarti a casa una Lamborghini nuova da 400.000€.',
    'lottery.messageEn': 'You have €20. One click. You could win a brand-new Lamborghini worth €400,000.',
    'lottery.close': 'Close',
    'lottery.joinButton': 'Join the Lottery',
    'lottery.comingSoon': 'Coming Soon',
    'lottery.back': 'Back',
    'lottery.heroText': 'Join Italy\'s most exclusive lottery. For just €20, you could win one of 19 exotic cars worth over 3 million euros in total.',
    'lottery.ticketTitle': 'Your Ticket',
    'lottery.prizePoolTitle': 'Exotic Cars Prize Pool',
    'lottery.totalValue': 'Total Value: Over €3,000,000',
    'lottery.rulesTitle': 'Rules & Regulations',
    'lottery.rule1': 'Ticket price is €20',
    'lottery.rule2': 'Public draw on October 30, 2025 with notary and lawyer',
    'lottery.rule3': 'Valid only with official receipt',
    'lottery.rule4': 'Tickets are limited and numbered',
    'lottery.rule5': 'Winner will be contacted within 24 hours of the draw',
    'lottery.rule6': 'All vehicles are brand new with official warranty',
    'lottery.ctaTitle': 'Don\'t Miss This Unique Opportunity',
    'lottery.ctaText': 'Buy your ticket now and you could drive home the exotic car of your dreams.',
    
    // Mileage rules
    'mileage.title': 'Included Kilometers',
    'mileage.day1': '1 day → 100 km',
    'mileage.day2': '2 days → 180 km',
    'mileage.day3': '3 days → 240 km',
    'mileage.day4': '4 days → 280 km',
    'mileage.day5': '5 days → 300 km',
    'mileage.day6Plus': 'From the 6th day onward → +60 km per day',
    'mileage.yourRental': 'Your {days}-day rental includes {km} km',
    
    // Villa Listings & Details
    'villa.listings.title': 'Luxury Villas',
    'villa.listings.subtitle': 'Discover our exclusive villas with 24/7 concierge services',
    'villa.listings.discoverMore': 'Discover more',
    'villa.listings.perNight': 'per night',
    'villa.listings.notFoundTitle': 'Can\'t find the perfect villa?',
    'villa.listings.notFoundDesc': 'Our concierge team can help you find the ideal accommodation for your needs',
    'villa.listings.contactConcierge': 'Contact the Concierge',
    
    'villa.details.theVilla': 'The Villa',
    'villa.details.comfortServices': 'Comfort & Services',
    'villa.details.interiorSpaces': 'Interior Spaces',
    'villa.details.position': 'Location',
    'villa.details.extraServices': 'Extra Services (on request)',
    'villa.details.guests': 'guests',
    'villa.details.rooms': 'rooms',
    'villa.details.bathrooms': 'bathrooms',
    'villa.details.checkIn': 'Check-in',
    'villa.details.checkOut': 'Check-out',
    'villa.details.select': 'Select',
    'villa.details.bookNow': 'Contact Us',
    'villa.details.instantConfirm': 'Instant confirmation via WhatsApp',
    'villa.details.cleaning': 'Cleaning',
    'villa.details.serviceFee': 'Service fee',
    'villa.details.total': 'Total',
    'villa.details.nights': 'nights',
    'villa.details.questionsTitle': 'Have questions about Villa Ambra?',
    'villa.details.questionsDesc': 'Our concierge team is available 24/7 for personalized assistance and exclusive services',
    'villa.details.contactTeam': 'Contact Our Concierge',
    'villa.details.bookingTitle': 'Booking',
    'villa.details.selectDates': 'Select dates to request information',
    'villa.amenities': 'Amenities',
    
    // Payment translations
    'securePayment': 'Secure Payment',
    'paymentAmount': 'Amount',
    'secureTransaction': 'Secure Transaction',
    'sslEncrypted': 'SSL Encrypted',
    'pciCompliant': 'PCI DSS Compliant',
    'nexiPaymentDescription': 'You will be redirected to Nexi secure payment gateway.',
    'cardTypesAccepted': 'We accept Visa, Mastercard, and other major cards.',
    'payNow': 'Pay Now',
    'processing': 'Processing...',
    'nexiPowered': 'Powered by Nexi',
    'paymentInitiated': 'Payment Initiated',
    'redirectedToNexi': 'You are being redirected to Nexi payment gateway.',
    'paymentError': 'Payment Error',
    'paymentSuccessful': 'Payment Successful!',
    'bookingConfirmed': 'Your booking has been confirmed and payment processed successfully.',
    'orderSummary': 'Order Summary',
    'vehicle': 'Vehicle',
    'transactionId': 'Transaction ID',
    'pickupDate': 'Pickup Date',
    'dropoffDate': 'Return Date',
    'totalPaid': 'Total Paid',
    'nextSteps': 'Next Steps',
    'confirmationEmailSent': 'A confirmation email has been sent to your email address.',
    'contractWillBeSent': 'The rental contract will be sent within 24 hours.',
    'prepareDocuments': 'Please prepare your driving license and ID for pickup.',
    'viewBookings': 'View My Bookings',
    'backToHome': 'Back to Home',
    'supportMessage': 'Need help? Contact our support team:',
    'paymentFailed': 'Payment Failed',
    'paymentFailedDescription': 'We were unable to process your payment.',
    'paymentNotProcessed': 'Unfortunately, your payment could not be processed.',
    'errorDetails': 'Error Details',
    'errorCode': 'Error Code',
    'errorMessage': 'Error Message',
    'possibleSolutions': 'Possible Solutions',
    'checkCardDetails': 'Check that your card details are correct',
    'checkCardBalance': 'Ensure your card has sufficient balance',
    'tryDifferentCard': 'Try using a different card',
    'contactBank': 'Contact your bank if the problem persists',
    'retryPayment': 'Retry Payment',
    'needHelp': 'Need Help?',
    'supportDescription': 'Our customer service team is here to help you resolve any payment issues.',
    'includeTransactionId': 'Please include this transaction ID when contacting support',
    'securityNotice': 'Your card details are secure and were not stored on our servers.',
    'cardDeclined': 'Card declined by issuing bank',
    'insufficientFunds': 'Insufficient funds',
    'invalidCard': 'Invalid card number',
    'expiredCard': 'Card expired',
    'authenticationFailed': 'Authentication failed',
    'transactionTimeout': 'Transaction timeout',
    'systemError': 'System error, please try again',
    'duplicateTransaction': 'Duplicate transaction',
    'securityViolation': 'Security violation detected',
    'cardNotSupported': 'Card type not supported',
    'unknownPaymentError': 'Unknown payment error',
    
    // Inline Eligibility Selectors
    'validation.ageRequired': 'Please confirm your age range.',
    'validation.countryRequired': 'Please select your country.',
    'validation.ageInconsistent.title': 'Age Mismatch',
    'validation.ageInconsistent.message': 'Your selected age doesn\'t match your date of birth.',
    'validation.ageInconsistent.short': 'Age doesn\'t match date of birth.',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('it'); // Default to Italian

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
